### PR TITLE
525-new-xcuitests

### LINKED ISSUE #525: XCUITests: New tests would be needed
Lets add more tests for:

- [ ] Entry detail view
   - [ ]  Open Website from there
   - [ ]  Copy option
 

- [ ] Search options

These are some examples without XCUITest coverage yet. Please feel free to add more so that we have test covering all the main features.

Thanks!

### LINKED ISSUE #542: XCUITest: test1LoginWithSavedLogins crashes intermittently
This test is failing due to two issues, one is issue #446 and and the other is the lack of error handling with empty values in the test. The reason is that the Confirm your account screen is shown for a while when the account is actually verified and no need to post code/uid is needed to verify it. Those values are empty in this case and so the test fails.

This crash is being managed in PR #530, in the latest runs the test is not crashing. Hopefully this will be fixed when this PR lands.

### LINKED ISSUE #582: Fix XCUITests around OAuth login flow
Merging #533 broke the uispecs :(

### PR DESCRIPTION
**Pull request by isabelrios**
Resolves #525
Fixes #542 
fixes #582

This PR adds a new test SearchOptions and improve the test for the checks done on a entry detailed view.

The LockboxScreenGraph has been modified to add some actions and the entry detail screen

### CODE REVIEW

**Comment by isabelrios** [comment]
Test test0LoginWithSavedLogins() is crashing due to this issue #446. It detects the Confirm your account, so it does the GET request to get the code and uid, but since the account is already verified those fields are empty and the test fails when trying to unwrap those values. Trying to find a fix for this since it is happening a lot lately in the tests when trying to get them green and remove the wip from this PR....

File: LockboxXCUITests/LockBoxScreenGraph.swift [hunk 1]
```diff
@@ -100,6 +105,18 @@ func createScreenGraph(for test: XCTestCase, with app: XCUIApplication) -> MMScr
...
+        screenState.tap(app.tables.cells.staticTexts.firstMatch, to: Screen.EntryDetails)
+    }
+
+    map.addScreenState(Screen.EntryDetails) { screenState in
+        screenState.gesture(forAction: Action.RevealPassword) { userState in
+            app.buttons["reveal.button"].tap()
+        }
+
+        screenState.gesture(forAction: Action.OpenWebsite) { userState in
+            app.cells["Web Address"].press(forDuration: 1)
```
Comment (jhugman) [inline LockboxXCUITests/LockBoxScreenGraph.swift]: This needs an `accessibilityIdentifier`.

File: LockboxXCUITests/LockboxXCUITests.swift [hunk 2]
```diff
@@ -75,25 +75,27 @@ class LockboxXCUITests: BaseTestCase {
...
-                done()
+            if (code != nil && uid != nil) {
+                let finalCodeIndex = code.index(code.endIndex, offsetBy: -32)
+                let codeNumber = code[finalCodeIndex...]
+                let finalUidIndex = uid.index(uid.endIndex, offsetBy: -32)
+                let uidNumber = uid[finalUidIndex...]
+
+                self.completeVerification(uid: String(uidNumber), code: String(codeNumber)) {
+                    done()
+                }
```
Comment (jhugman) [inline LockboxXCUITests/LockboxXCUITests.swift]: This looks complicated; can you simplify the logic by using `guard` statements?

File: LockboxXCUITests/LockboxXCUITests.swift [hunk 3]
```diff
@@ -140,17 +142,21 @@ class LockboxXCUITests: BaseTestCase {
 
         XCTAssertTrue(app.navigationBars["Firefox Lockbox"].exists)
         XCTAssertTrue(app.navigationBars.buttons["Settings"].exists)
-        snapshot("02EntryList" + CONTENT_SIZE)
 
         sleep(5)
+        var i = 0
+        repeat {
+            i = i+1
+        } while (app.staticTexts["Confirm your account."].exists == true && i < 8)
```
[the remark this answers is not in the document]
Comment (isabelrios) [reply LockboxXCUITests/LockboxXCUITests.swift]: I was not happy with that solution either but need a workaround for issue #446. If that ```Confirm your account screen``` is shown, we go to verify the account so that we can log in after the account is verified. The problem is that sometimes that screen is shown for a while when the account does not need to be verified.
`waitForNoExistence`does not work, since it will fail in the case where we actually need to verify the account and that screen is not going to disappear until that's done. 
So we need to wait and check if the ```Confirm your account screen``` disappears after a while or not to continue with the test according to the real status of the account.

I will work on this and try to find a better solution.

File: LockboxXCUITests/LockBoxScreenGraph.swift (hunk 1 above)
Comment (isabelrios) [reply LockboxXCUITests/LockBoxScreenGraph.swift]: If I'm not wrong, that's already an identifier:

```
Cell, 0x600000197f80, traits: 8589934592, {{0.0, 151.0}, {375.0, 58.0}}, identifier: 'Web Address', label: 'Web address: double tap to open in browser https://accounts.google.com'
```

File: LockboxXCUITests/LockboxXCUITests.swift (hunk 2 above)
Comment (isabelrios) [reply LockboxXCUITests/LockboxXCUITests.swift]: 👍 I will try to simplify it.
Thanks!

File: LockboxXCUITests/LockboxXCUITests.swift [hunk 4]
```diff
@@ -185,26 +192,56 @@ class LockboxXCUITests: BaseTestCase {
...
+        XCTAssertEqual(passwordValueReveal, "test15mz")
+
+        // Check the copy functionality with user name
+        let userNameField = app.cells["Username"]
+        userNameField.press(forDuration: 1)
+
+        // Now check the clipboard
+        if let userNameString = UIPasteboard.general.string {
+            let value = app.cells["Username"].staticTexts.element(boundBy: 1).label
+            XCTAssertNotNil(userNameString)
```
[the remark this answers is not in the document]
Comment (isabelrios) [reply LockboxXCUITests/LockboxXCUITests.swift]: Yes, sorry, you are right, just changed that

**Comment by isabelrios** [comment]
Thanks for your review @jhugman!! I did some modifications to the code. Hope it looks better now.

I tried to use `guard` statements where you suggested but I did not get the tests working using them.  When `uid` or `code` are nil and the statement returns in the else, it exits in a way that the completion handler is not executed and the test never ends. Is at least a little bit simplier the logic using the function to deal with the strings and get the `uid` or `code` values? 
Thanks!

**Comment by devinreams** [comment]
Noted during a quick backlog review: @jhugman and @sashei should come back for another code review here.

File: LockboxXCUITests/LockBoxScreenGraph.swift (hunk 1 above)
Comment (sashei) [reply LockboxXCUITests/LockBoxScreenGraph.swift]: It doesn't follow the pattern of our other `accessibilityIdentifier`s though, you're right.... I can fix the `ItemDetail` accessibilityIDs on this branch if that's an acceptable solution to this issue.

File: LockboxXCUITests/LockboxXCUITests.swift [hunk 5]
```diff
@@ -236,17 +273,25 @@ class LockboxXCUITests: BaseTestCase {
...
-    func test7EntryDetails() {
+    func test6SortEntries() {
         navigator.goto(Screen.LockboxMainPage)
-        waitforExistence(app.tables.cells.staticTexts["iosmztest@gmail.com"])
-        app.tables.cells.staticTexts["iosmztest@gmail.com"].tap()
-        XCTAssertTrue(app.tables.cells.staticTexts["Web Address"].exists)
-        XCTAssertTrue(app.tables.cells.staticTexts["Username"].exists)
-        XCTAssertTrue(app.tables.cells.staticTexts["iosmztest@gmail.com"].exists)
-        XCTAssertTrue(app.tables.cells.staticTexts["Password"].exists)
+        waitforExistence(app.navigationBars["Firefox Lockbox"], timeout: 10)
```
Comment (sashei) [inline LockboxXCUITests/LockboxXCUITests.swift]: Do we want an `accessibilityIdentifier` for this navigation bar, also?

Comment (isabelrios) [reply LockboxXCUITests/LockboxXCUITests.swift]: I have already modified this, is the same here, that is already an `accessibilityIdentifier`, but with the name not following the pattern.

File: LockboxXCUITests/LockBoxScreenGraph.swift (hunk 1 above)
Comment (isabelrios) [reply LockboxXCUITests/LockBoxScreenGraph.swift]: Oh I see, yup, the pattern is different. So, we have the same issue with the `accessibilityIdentifier`s  in `settingsView` , please see [here](https://github.com/mozilla-lockbox/lockbox-ios/blob/master/LockboxXCUITests/LockBoxScreenGraph.swift#L119). Identifiers are set but they name used is the `cellConfiguration.text`, and do not follow the pattern either.
I was trying to fix them all but have not found how to do it correctly yet. Only got the `Firefox Lockbox` (navigationBar) 
If you want to fix them in this branch is great, but if you prefer I can try to do it with some guidance, what is faster for you. Both ways I will learn how to do it so that I can do it by myself next time.
Thank you!!

Comment (jhugman) [reply LockboxXCUITests/LockBoxScreenGraph.swift]: I'd be really happy for you to be able to fix them for yourself.

The quickest way I have found is to start with the text and trace it back to the view itself. e.g. 

for a view with the label: `Example View`, 

 * searching all files in Xcode for the text `Example View` reveals the declaration of `AppConstants.labelExampleView`
 * searching all files in Xcode for the `labelExampleView` reveals where it is used to set the label text. This is likely where the label is constructed.
 * where it is constructed, you can add your own `accessibilityIdentifier`.

For how to set the identifier: pick the pattern that existing views have used and use that — but I don't think this is something you're having problems with.

Comment (isabelrios) [reply LockboxXCUITests/LockBoxScreenGraph.swift]: Thanks for your suggestion @jhugman.
Finally I was able to find a way to add the `accessibilityIdentifier`s for the Settings options and also for the Item Detail options. Not sure if that is correct or there is a simplier way. 
@sashei, @jhugman Could you please let me know how it looks now? 
Thanks!

Comment (jhugman) [reply LockboxXCUITests/LockBoxScreenGraph.swift]: I think it'd be great if @isabelrios would take ownership of the `accessibilityIdentifier`s. Go with whatever pattern that makes sense (i.e. follow what is already there), but make it different from the label itself.

Comment (jhugman) [reply LockboxXCUITests/LockBoxScreenGraph.swift]: Please ping either sasha or I on how to find where to add accessibility identifiers if you need help.

File: LockboxXCUITests/LockboxXCUITests.swift [hunk 6]
```diff
@@ -176,34 +183,64 @@ class LockboxXCUITests: BaseTestCase {
         XCTAssertTrue(app.buttons["disconnectFirefoxLockbox.button"].exists, "The option to disconnect does not appear")
     }
 
-    func test3SettingOpenWebSitesIn() {
+    func test2SettingOpenWebSitesIn() {
```
Comment (jhugman) [inline LockboxXCUITests/LockboxXCUITests.swift]: Do the tests need to be numbered?

File: LockboxXCUITests/LockboxXCUITests.swift [hunk 7]
```diff
@@ -176,34 +183,64 @@ class LockboxXCUITests: BaseTestCase {
...
+        // Check the copy functionality with user name
+        let userNameField = app.cells["Username"]
+        userNameField.press(forDuration: 1)
+
+        // Now check the clipboard
+        if let userNameString = UIPasteboard.general.string {
+            let value = app.cells["Username"].staticTexts.element(boundBy: 1).label
+            XCTAssertNotNil(value)
+            XCTAssertEqual(userNameString, value, "Url matches with the UIPasteboard")
+        }
```
Comment (jhugman) [inline LockboxXCUITests/LockboxXCUITests.swift]: What happens if there is nothing on the pasteboard. Isn't this a failure?

File: LockboxXCUITests/LockboxXCUITests.swift [hunk 8]
```diff
@@ -258,6 +303,42 @@ class LockboxXCUITests: BaseTestCase {
...
+        XCTAssertEqual(oneMatches, 1)
+
+        // There should not be any matches
+        searchTextField.typeText("x")
+        sleep(2)
+
+        let noMatches = app.tables.cells.count-1
+        XCTAssertEqual(noMatches, 1)
+        XCTAssertEqual(app.cells.staticTexts.element(boundBy: 1).label, "No matching entries.")
+
```
Comment (jhugman) [inline LockboxXCUITests/LockboxXCUITests.swift]: Nit: whitespace

File: LockboxXCUITests/LockboxXCUITests.swift [hunk 9]
```diff
@@ -258,6 +303,42 @@ class LockboxXCUITests: BaseTestCase {
...
+        XCTAssertEqual(twoMatches, 2)
+
+        // There should be one match
+        searchTextField.typeText("cc")
+        let oneMatches = app.tables.cells.count-1
+        XCTAssertEqual(oneMatches, 1)
+
+        // There should not be any matches
+        searchTextField.typeText("x")
+        sleep(2)
```
Comment (jhugman) [inline LockboxXCUITests/LockboxXCUITests.swift]: Please add a comment on why `sleep` is necessary. Or try and avoid adding `sleep`s.

File: LockboxXCUITests/LockboxXCUITests.swift [hunk 10]
```diff
@@ -258,6 +303,42 @@ class LockboxXCUITests: BaseTestCase {
...
+
+        let noMatches = app.tables.cells.count-1
```
Comment (jhugman) [inline LockboxXCUITests/LockboxXCUITests.swift]: Nit: whitespace. `count - 1`.

File: LockboxXCUITests/LockboxXCUITests.swift (hunk 6 above)
Comment (isabelrios) [reply LockboxXCUITests/LockboxXCUITests.swift]: So far yes, the way the are written (not perfect but first approach) is to log in once and run all the tests. The number is to control the order when running the tests. 
This will be fixed in #531 where each test is independent. We have to introduce more logic and checks before each test, but at least they will be independent from previous tests and results.

**Comment by isabelrios** [comment]
After the [PR with the new OAuth](https://github.com/mozilla-lockbox/lockbox-ios/pull/533) flow landed, I need to fix the tests according to new implementation

**Comment by isabelrios** [comment]
@jhugman @sashei Could you please review this PR? XCUITests are failing on master and would be good to have them back working soon.
- I tried to fix all the previous comment in previous reviews
- Here I added as much acc.IDs as I could, for the rest I will open a follow up if you agree. As discussed in previous issue #479 for Alphabetically and Recently Used option sheet some private API accessing / hackery is needed. So lets do that in a follow up so that this PR does not get super big (more than what it is already)
- Tests are working with new OAuth flow
- SortingEntries test is failing on BB, so I have disabled one check for it to be added as soon as that issue is gone.

File: LockboxXCUITests/LockBoxScreenGraph.swift [hunk 11]
```diff
@@ -116,9 +130,9 @@ func createScreenGraph(for test: XCTestCase, with app: XCUIApplication) -> MMScr
     }
 
     map.addScreenState(Screen.SettingsMenu) { screenState in
-        screenState.tap(app.tables.cells.staticTexts["Open Websites in"], to: Screen.OpenSitesInMenu)
-        screenState.tap(app.tables.cells.staticTexts["Account"], to: Screen.AccountSettingsMenu)
-        screenState.tap(app.tables.cells.staticTexts["Auto Lock"], to: Screen.AutolockSettingsMenu)
+        screenState.tap(app.tables.cells["openWebSitesInSettingOption"], to: Screen.OpenSitesInMenu)
+        screenState.tap(app.tables.cells["accountSettingOption"], to: Screen.AccountSettingsMenu)
+        screenState.tap(app.tables.cells["autoLockSettingOption"], to: Screen.AutolockSettingsMenu)
```
Comment (jhugman) [inline LockboxXCUITests/LockBoxScreenGraph.swift]: Nice.

File: LockboxXCUITests/LockboxXCUITests.swift (hunk 6 above)
Comment (jhugman) [reply LockboxXCUITests/LockboxXCUITests.swift]: 👍

**Comment by devinreams** [comment]
Thanks for all of this, @isabelrios. And thanks to @jhugman and @sashei for helping review.

@isabelrios are you ok and ready for me to merge this? I’ll re-enable the “errors = fail” setting on buddybuild afterwards.

**Comment by isabelrios** [comment]
Thanks for your help to have this done!! 
@devinreams Yes, I think this could be merged. Tests are passing pretty consistently, so yes, I would enable that flag again so we do not miss real issues. I will be paying attention to the XCUITests and if there is any intermittent failure will let you know to disable temporary that flag until there is a fix. 
Thanks!
