### PR TITLE
531-xcuites-refactor-new-attempt

### LINKED ISSUE #531: XCUITests: Make tests independent from previous tests
So far the approach to run the tests is to log in in the first test and test the app in the following ones until we disconnect in the last test.
This is not good because if one test fails, it will most likely make the next test to fail too. On the other hand, with this solution we avoid the log in in each test that could cause a lot of issues since we rely on the FxAccount Log in Sync site that depending on the network takes a different time to load and could cause some timing issues.

I'm trying to find a solution in which we have more stable and independent test. For that I'm comparing the issues we could see by logging in in each test versus something similar to what we have now.

Suggestions are more than welcome :)

### PR DESCRIPTION
**Pull request by isabelrios**
Fixes #531 

This PR is based on the work done on previous PR #754.
In addition, the test account has changed. Instead of using the previous one in which the verification was needed we are using the test account that does not need that step. That simplifies the login code and so the tests.

The tests run independently now. The app is removed and re-installed after each test.
There are functions not added to the graph because it does not work with conditionals and so the transition from one screen to another in the onboarding for example would not work depening on the iOS version.

### CODE REVIEW

**Comment by isabelrios** [comment]
@sashei I would like to know your opinion about these changes. Also if this PR fixes the app lifecycle issue. Thanks!

File: LockboxXCUITests/LockBoxScreenGraph.swift [hunk 1]
```diff
@@ -201,102 +213,57 @@ func createScreenGraph(for test: XCTestCase, with app: XCUIApplication) -> MMScr
...
-
-            if let rangeCode = responseString?.range(of:regexCode, options: .regularExpression) {
-                code = String(responseString![rangeCode])
-            }
-
-            if (code != nil && uid != nil) {
-                let codeNumber = self.getPostValues(value: code)
-                let uidNumber = self.getPostValues(value: uid)
+    func waitForLockboxEntriesListView() {
+        waitforExistence(app.navigationBars["firefoxLockbox.navigationBar"])
```
Comment (sashei) [inline LockboxXCUITests/LockBoxScreenGraph.swift]: nice, I really like this function!! I think sync is getting kicked off slowly with some of the rust changes and this is a good workaround.

File: LockboxXCUITests/LockboxXCUITests.swift [hunk 2]
```diff
@@ -4,87 +4,29 @@
...
-        let restUrl = URL(string: deleteEndPoint)
-        var request = URLRequest(url: restUrl!)
-        request.httpMethod = "DELETE"
-
-        let task = URLSession.shared.dataTask(with: request) { data, response, error in
-            print("Delete")
-        }
-        task.resume()
-        super.setUp()
+    override func tearDown() {
```
Comment (sashei) [inline LockboxXCUITests/LockboxXCUITests.swift]: 🙌

File: LockboxXCUITests/LockboxXCUITests.swift [hunk 3]
```diff
@@ -118,38 +60,73 @@ class LockboxXCUITests: BaseTestCase {
 
         // Open website Web Address
         let webAddressValue = app.cells["webAddressItemDetail"].staticTexts.element(boundBy: 1).label
-        XCTAssertEqual(webAddressValue, "https://accounts.google.com")
+        XCTAssertEqual(webAddressValue, websiteDetailView)
```
Comment (sashei) [inline LockboxXCUITests/LockboxXCUITests.swift]: having these as constants is great!

File: LockboxXCUITests/LockboxXCUITests.swift [hunk 4]
```diff
@@ -4,87 +4,29 @@
...
-
-        if #available(iOS 12.0, *) {
-            waitforExistence(app.buttons["setupAutofill.button"])
-            navigator.performAction(Action.NotAutofillSetUpNow)
-        }
-        waitforExistence(app.buttons["finish.button"])
-        navigator.goto(Screen.LockboxMainPage)
-
-        waitforExistence(app.tables.cells.staticTexts[firstEntryEmail], timeout: 15)
+        loginFxAccount()
```
Comment (sashei) [inline LockboxXCUITests/LockboxXCUITests.swift]: 😍  love the new descriptive method names, this is feeling like the android ui tests!

File: LockboxXCUITests/LockboxXCUITests.swift [hunk 5]
```diff
@@ -170,25 +147,12 @@ class LockboxXCUITests: BaseTestCase {
...
-        // Send app to background and launch it
-        XCUIDevice.shared.press(.home)
-        app.activate()
-        waitforExistence(app.tables.cells.staticTexts["iosmztest@gmail.com"])
-    }
-    
-    func test8SearchOptions() {
-        navigator.goto(Screen.LockboxMainPage)
+        // Search entries options
         sleep(5)
```
Comment (sashei) [inline LockboxXCUITests/LockboxXCUITests.swift]: can you use another `waitForExistence` here?

File: LockboxXCUITests/LockboxXCUITests.swift [hunk 6]
```diff
@@ -197,18 +161,17 @@ class LockboxXCUITests: BaseTestCase {
         // There should be two matches
         let twoMatches = app.tables.cells.count
```
Comment (sashei) [inline LockboxXCUITests/LockboxXCUITests.swift]: maybe this name could be updated, given that there are far more than two matches :)

File: LockboxXCUITests/LockboxXCUITests.swift [hunk 7]
```diff
@@ -197,18 +161,17 @@ class LockboxXCUITests: BaseTestCase {
...
-            XCTAssertEqual(twoMatches, 5)
+            XCTAssertEqual(twoMatches, 111)
         } else {
-            XCTAssertEqual(twoMatches, 2)
+            XCTAssertEqual(twoMatches, 108)
         }
-        
         // There should be one match
         searchTextField.typeText("cc")
         let oneMatches = app.tables.cells.count
```
Comment (sashei) [inline LockboxXCUITests/LockboxXCUITests.swift]: same with this variable name.

File: LockboxXCUITests/LockboxXCUITests.swift [hunk 8]
```diff
@@ -219,21 +182,36 @@ class LockboxXCUITests: BaseTestCase {
...
+        navigator.nowAt(Screen.LockboxMainPage)
     }
 
-    func test9LockNowUnlock() {
+    func testCheckAutolock() {
+        loginFxAccount()
+        // Check if the account is verified and if not, verify it
+        skipAutofillConfiguration()
+        tapOnFinishButton()
+        waitForLockboxEntriesListView()
```
Comment (sashei) [inline LockboxXCUITests/LockboxXCUITests.swift]: would it be a good idea to unify these login methods into one `loginToEntryListView` or something similar? it seems like they are repeated for most of the tests.

File: LockboxXCUITests/LockBoxScreenGraph.swift [hunk 9]
```diff
@@ -201,102 +213,57 @@ func createScreenGraph(for test: XCTestCase, with app: XCUIApplication) -> MMScr
...
-            let group = DispatchGroup()
-            group.enter()
-            DispatchQueue.global(qos: .userInitiated).async { [weak self] in
-                self?.verifyAccount() {
-                    group.leave()
-                }
+    func skipAutofillConfiguration() {
+        if #available(iOS 12.0, *) {
+            //If autofill is set this option will not appear
+            sleep(5)
```
[the remark this answers is not in the document]
Comment (isabelrios) [reply LockboxXCUITests/LockBoxScreenGraph.swift]: This is the only thing I can't fix, depending on the autofill setting the option will be available or not. I can't use a `waitForExistence` it will fail if the option is set previously. I know is not a good solution but don't know what else I could do...

File: buddybuild_prebuild.sh [hunk 10]
```diff
@@ -2,4 +2,9 @@
 echo "Setting SentryDSN to $SENTRY_DSN"
 /usr/libexec/PlistBuddy -c "Set SentryDSN $SENTRY_DSN" "lockbox-ios/Common/Resources/Info.plist"
 
+if ! [ -x "$(command -v swiftlint)" ] ; then
```
Comment (isabelrios) [inline buddybuild_prebuild.sh]: @sashei last question before landing...I was having [BB error ]([url](https://dashboard.buddybuild.com/apps/5a0ddb736e19370001034f85/build/5cc6c664fde6cb00016f9b75#logs))with swift already installed, 
```
    Error: swiftlint 0.27.0 is already installed
    To upgrade to 0.32.0, run `brew upgrade swiftlint`.
```
it may be only an issue until may 6th when they stop installing it...but at least as a workaround until then I changed this script...is that fine or do you prefer a better solution? Thanks!
