### PR TITLE
stay locked when returning from background

### LINKED ISSUE #699: App not staying locked when canceling out of Biometrics/Passcode prompt
Not sure when this got introduced, but there appears to be an issue with the app staying locked when you cancel out of an auth prompt (for biometrics or passcode), background, then foreground the app. Screen captures below:

biometrics

passcode

### LINKED ISSUE #715: Lockbox can be unlocked without using biometrics
Build: 15e1604
Device: iPhone 7
iOS: 12b6

Preconditions:
- Clean install
- Log in to Lockbox
- Enable Autofill for Lockbox from iOS settings
- Autolock timer set to 1 minute

Steps to reproduce:
1.  Open Lockbox
2. From Settings tap on "Lock Now" 
3. Background Lockbox
4. Open iOS Settings -> Autofill Passwords
5. Uncheck Autofill Passwords for Lockbox
6. Check  Autofill Passwords for Lockbox
7. Forground Lockbox

Actual results:
- Lockbox will be unlocked without using biometrics.

Video here: https://www.youtube.com/watch?v=bhxiB6g5rc4

Note: 
- This issue is not always reproducible. Sometimes repeating steps 3) to 7) is necessary.

### PR DESCRIPTION
**Pull request by sashei**
resolves #699 
resolves #715

### CODE REVIEW

File: Shared/Store/BaseAutoLockStore.swift [hunk 1]
```diff
@@ -5,27 +5,22 @@
...
     init(dispatcher: Dispatcher = Dispatcher.shared,
          dataStore: DataStore = DataStore.shared,
-         userDefaults: UserDefaults = UserDefaults(suiteName: Constant.app.group) ?? .standard,
-         keychainWrapper: KeychainWrapper = KeychainWrapper(serviceName: "", accessGroup: Constant.app.group)
-    ) {
+         userDefaults: UserDefaults = UserDefaults(suiteName: Constant.app.group) ?? .standard) {
         self.dispatcher = dispatcher
         self.userDefaults = userDefaults
-        self.keychainWrapper = keychainWrapper
         self.dataStore = dataStore
```
Comment (jhugman) [inline Shared/Store/BaseAutoLockStore.swift]: This hunk is just tidying.

File: lockbox-ios/Store/AutoLockStore.swift [hunk 2]
```diff
@@ -45,7 +59,9 @@ class AutoLockStore: BaseAutoLockStore {
             })
             .disposed(by: self.disposeBag)
 
-        self.dispatcher.register
+        Observable.combineLatest(self.dispatcher.register, self.dataStore.locked)
+            .filter { !$0.1 }
+            .map { $0.0 }
```
Comment (jhugman) [inline lockbox-ios/Store/AutoLockStore.swift]: This is the bit that does the work.

File: lockbox-iosTests/AutoLockStoreSpec.swift [hunk 3]
```diff
@@ -61,10 +61,12 @@ class AutoLockStoreSpec: QuickSpec {
             }
 
             describe("foregrounding app") {
-                describe("when the app is on a webview") {
+                describe("when the app is on a webview and is unlocked") {
```
Comment (jhugman) [inline lockbox-iosTests/AutoLockStoreSpec.swift]: Nice.

File: lockbox-iosTests/AutoLockStoreSpec.swift [hunk 4]
```diff
@@ -78,6 +80,8 @@ class AutoLockStoreSpec: QuickSpec {
                 describe("when the app is not on a webview") {
                     beforeEach {
                         self.userDefaults.set((Date().timeIntervalSince1970 - 3), forKey: UserDefaultKey.autoLockTimerDate.rawValue)
+
+                        self.dataStore.lockedStub.onNext(false)
                         self.userDefaults.set(Setting.AutoLock.FiveMinutes.rawValue, forKey: UserDefaultKey.autoLockTime.rawValue)
                         self.dispatcher.registerStub.onNext(LifecycleAction.foreground)
                     }
```
Comment (jhugman) [inline lockbox-iosTests/AutoLockStoreSpec.swift]: Nit: Is there already a test for when 

```swift
lockedStub.onNext(true)
```
