### PR TITLE
Welcome screen fixes for iPhone SE

### LINKED ISSUE #501: "Learn more" link is too bottom aligned on iPhone SE
v1.1 (1490)
iPhone SE iOS 10.3.3

Steps to reproduce:
1. Install Lockbox

Actual results:
- The "Learn more" link is too bottom aligned.

screen shot 2018-06-26 at 2 56 51 pm

### LINKED ISSUE #502: Welcome page layout breaks after tapping on "Learn more" link
v1.1 (1490)
iPhone SE iOS 10.3.3

Steps to reproduce:
1. Install Lockbox
2. Tap on "Learn more" link
3.  Close the "Learn more" page

Actual results:
- Welcome page layout is broken and shifted down.

screen shot 2018-06-26 at 3 33 08 pm

### PR DESCRIPTION
**Pull request by devinreams**
- Fixes #502: a placeholder / nav bar is being added when you click "Learn More" which isn't needed since the FxAView has its own "Close" nav bar that slides up and over
- Fixes #501: I adjusted the constraints and shifted things up a little bit so the "Learn More" has a bit more breathing room at the bottom of the iPhone SE screen

## Before

screen shot 2018-06-26 at 10 18 46 am

screen shot 2018-06-26 at 10 24 11 am

## After

screen shot 2018-06-26 at 10 24 09 am

screen shot 2018-06-26 at 10 44 21 am

---

I also re-tested the screen on iPhone 8 and iPhone X and I don't think I broke / regressed on anything else.

### CODE REVIEW

File: lockbox-ios/View/WelcomeView.swift [hunk 1]
```diff
@@ -44,32 +44,15 @@ class WelcomeView: UIViewController {
...
         self.navigationController?.setNavigationBarHidden(true, animated: false)
     }
 
     override func viewWillDisappear(_ animated: Bool) {
         super.viewDidDisappear(animated)
-        self.navigationController?.setNavigationBarHidden(false, animated: false)
+        self.navigationController?.setNavigationBarHidden(true, animated: false)
     }
 
-    private func setupNavbar() {
```
Comment (sashei) [inline lockbox-ios/View/WelcomeView.swift]: \>.<
