### PR TITLE
Use bytesNoCopy:length:encoding:freeWhenDone:

### LINKED ISSUE #120: `Garbage at end` from FxA decryption results in app crash
Sometimes part of the FxA login results in the following error: `Error Domain=NSCocoaErrorDomain Code=3840 "Garbage at end." UserInfo={NSDebugDescription=Garbage at end.}`

As a result, the user is not logged in, and cancelling & trying to login again crashes the app. This happens intermittently, and subsequent login attempts are successful.

#### devices
- iPhone 8 11.2 simulator
- iPhone 5 10.3 simulator

### PR DESCRIPTION
**Pull request by sashei**
import non-null-terminated cstrings safely

resolves #120

### CODE REVIEW

File: lockbox-ios/Common/Helpers/KeyManager.swift [hunk 1]
```diff
@@ -18,15 +18,17 @@ class KeyManager {
...
-    func decryptJWE(_ jwe: String) -> String {
+    func decryptJWE(_ jwe: String) -> String? {
         let count = jwe.data(using: .utf8)!.count as size_t
         let contentLen = UnsafeMutablePointer<size_t>.allocate(capacity: count)
         let err = UnsafeMutablePointer<cjose_err>.allocate(capacity: count)
 
         let cJoseJWE = cjose_jwe_import(jwe, count, nil)
-        let decryptedPayload = cjose_jwe_decrypt(cJoseJWE, self.jwk, contentLen, err)
+        guard let decryptedPayload = cjose_jwe_decrypt(cJoseJWE, self.jwk, contentLen, err) else {
+            return nil
```
Comment (linuxwolf) [inline lockbox-ios/Common/Helpers/KeyManager.swift]: The only reason `cjose_jwe_decrypt()` returns `NULL` is if it fails.  This might want to "throw" `err` in some form, or at least log it somehow.

## background ##
[`cjose_err`](http://cisco.github.io/cjose/structcjose__err.html) is a structure with a bunch of static values in it, but the most relevant for logs (if nothing else) are:

* `code` describing the error in a machine-readable way
* `message` canned text describing the error for a human (more or less)

File: lockbox-ios/Common/Helpers/KeyManager.swift [hunk 2]
```diff
@@ -18,15 +18,17 @@ class KeyManager {
...
+        }
 
-        return String(cString: decryptedPayload!)
+        return String(bytesNoCopy: decryptedPayload, length: contentLen.pointee, encoding: .utf8, freeWhenDone: true)
```
Comment (linuxwolf) [inline lockbox-ios/Common/Helpers/KeyManager.swift]: CJOSE allows API users to configure what implementation of `malloc` / `realloc` /  `free` is used (by default, whatever it picks up from `libc` or its moral equivalent).

Not knowing enough about Swift, I don't know if there's a concern about deallocation here, but I'm going to assume not if everything passes BuddyBuild (-:
