### PR TITLE
autolock when appropriate on app foreground

### LINKED ISSUE #566: Autolock timer does not lock the app
Opposite of #463 

Something may have regressed. We have two potentially related PRs #537 #551 that may have introduced a change that causes the timer not to lock. But when I tried testing against both I couldn't isolate and find which (if either) actually caused a problem ... because they both ended up working just fine for me.

@sandysage and @nickbrandt have experienced inconsistencies where some timers do work, then timers don't work at all.  So I wonder if there is a userdefaults or data problem?

Opening this issue to try to gather more data points from folks and, ideally, really consistent steps to reproduce the problem.

### LINKED ISSUE #571: Logins are not displayed “No entries found” after restarting the app
Build: master 6b50a172
Device: iPhone 8 iOS 11.3

Steps to reproduce:
1. Launch Lockbox after a clean install
2. Tap "Get Started"
3. Login to FxA and wait for logins to sync
4. Force close Lockbox from app switcher
5. Re-open Lockbox

Actual results:
- No logins are displayed. 

Note:
- This is also happening when Reinstalling the same version over the existing app.

### PR DESCRIPTION
**Pull request by sashei**
resolves #566 
resolves #571

### CODE REVIEW

File: lockbox-ios/Store/AutoLockStore.swift [hunk 1]
```diff
@@ -98,13 +108,15 @@ extension AutoLockStore {
 
     private func setTimer(seconds: Int) {
         let timerValue = self.userDefaults.double(forKey: SettingKey.autoLockTimerDate.rawValue)
-        if timerValue != 0 && timerValue < Date().timeIntervalSince1970 {
+        if timerValue != 0 && timerValue > Date().timeIntervalSince1970 {
```
Comment (linuxwolf) [inline lockbox-ios/Store/AutoLockStore.swift]: * If `timerValue` is in the future, create a timer for that future date
* If `timerValue` is in the past, lock now
* Otherwise (assuming `timerValue` is not set or is **right now**) update the timer.

This seems to mean the timer is only updated if it's been cleared, or if `timerValue` happens to be the exact date/time.  It does not update from user interactions ...

Comment (linuxwolf) [reply lockbox-ios/Store/AutoLockStore.swift]: corrected about the first point (read `resetTimer()` as `setupTimer()` for the interaction Actions handling).

**Comment by nickbrandt** [comment]
Also tested signing in and changing to 1 minute timer:

- Went back to Entry List, waited 1 min > Locked ✅ 
- Opened up FAQ screen, waited over 1 min > Did **not** lock ✅ 
- Opened up Provide Feedback screen, waited over 1 min > Did **not** lock ✅ 
- Went to "Open Websites In" screen, waited over 1 min > Did **not** lock ❌ 
- Went back to Entry List (now showing No Results screen 🤷‍♂️ ), waited over 1 min > Did **not** lock ❌ 
- Backgrounded app, waited over 1 min, returned > **Not** locked ❌ 
- Force quit app, re-opened, waited 1 min > Locked ✅ 
- Went to Account screen, waited 1 min > Locked ✅ 

Worked as expected for the most part, but still experiencing a few issues...

**Comment by devinreams** [comment]
I tried reproducing your steps @nickbrandt and can: it did not lock on the settings screen, “No entries found” when returning to list #571, did not lock on that list view nor in background again.

@sashei I cannot tell, is the app expected to lock on a settings screen like “Open Websites In”? Is there something different about it that would “break” the timer and prevent it from running afterwards?

**Comment by sashei** [comment]
I think it would be expected to lock on a settings screen as well.

**Comment by devinreams** [comment]
>I think it would be expected to lock on a settings screen as well.

Agreed. Are you suggesting that be considered and addressed here (and you're already planning on it)? Or should we file a separate issue?

**Comment by sashei** [comment]
Err, I think that should be a rejection on this ticket. I'll address it here but I left my physical device in the office and I'm not able to replicate on the simulator so I will revisit this on Friday.

**Comment by devinreams** [comment]
I just reproduced this and think it has to do with the status of "paused" introduced at #537.

- Freshly installed app
- Changed timer setting to 1 minute
- Opened "Open Websites In" settings screen
- App locked after 1 minute ✅ 

Versus:

- Opened "FAQ" (webpage) screen
- Waited 1 minute
- App did not lock ✅
- Opened "Open Websites In" settings screen
- App did not lock after 1 minute ❌ 

So the guess is something is not re-calling setTimer to get a new timer running. Note I never go back to an entry or list, just stay within the settings screens...

**Comment by sashei** [comment]
Ok! I figured this out, subtle bug.....

I return with a product question... If you are on a webpage (such as the FAQ) and background the app, should it lock when you return to the foreground?

I also think that this bug is related to all of the `No Entries Found` issues we've been having ....

**Comment by sashei** [comment]
@changecourse @nickbrandt ^ product question

**Comment by changecourse** [comment]
@sashei yes, I think it should lock if 'backgrounded,' based on set time, regardless of while in a webview or in the app itself. 

This may, in rare instances, adversely affect someone entering feedback, but I doubt it would occur often enough to merit concern.

**Comment by sashei** [comment]
ok! I think this is in a testable state again. 

I made the specs optional on this branch so that others can do some functional testing before I go through and finish up the specs (also specs broken on master 😥)

**Comment by devinreams** [comment]
I just reproduced this and think it has to do with the status of "paused" introduced at #537.

- Freshly installed app
- Changed timer setting to 1 minute
- Opened "Open Websites In" settings screen
- App locked after 1 minute ✅ 

And also!

- Opened "FAQ" (webpage) screen
- Waited 1 minute
- App did not lock ✅
- Opened "Open Websites In" settings screen
- App did lock after 1 minute ✅ 

And also!

- Returned to entry list
- App did lock after 1 minute ✅ 

And also:

- Sent the app to the background
- Re-opened app after 1 minute and it was locked ✅ 

And also:

- Force quit the app
- Re-opened app after 1 minute and it was locked ✅ 

---

@nickbrandt would you like to give it one final run through on your side just to help make sure we didn't accidentally overlooking anything?

**Comment by nickbrandt** [comment]
Tested as follows:
- Signed in and changed to 1 minute timer
- Went to Preferred Browser screen > waited 1 min > Locked as expected
- Went to Send Feedback > waited over 1 min > Did **not** lock as expected
- Went to FAQ > backgrounded app > waited over 1 min > returned to app > Locked as expected
- Returned to Entry List > waited 1 min > Locked as expected

Everything appears good on my end!
